name: C++20 Finite Element Codes Build Test

on:
  push:
    branches: ["main", "dev_1"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Repository Code
      uses: actions/checkout@v4

    - name: Compile Solver
      run: |
        cd cpp
        cmake -B build
        cmake --build build

    - name: Configure CMake
      # Force GCC-13 for C++20 <format> support on the runner
      run: cmake -B build -DCMAKE_CXX_COMPILER=g++-13 

    - name: Build
      run: cmake --build build

    # Add this final step!
    - name: Run Unit Tests
      run: |
        cd build
        ctest --output-on-failure
