name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This acts like 'cd cpp' for the entire server
    defaults:
      run:
        working-directory: ./cpp

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_COMPILER=g++-13 

      - name: Build
        run: cmake --build build

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure
